package:
  name: magma
  version: 2.2.0

source:
   url: http://icl.cs.utk.edu/projectsfiles/magma/downloads/magma-2.2.0.tar.gz
   patches:
     - cmakelists.patch
     - thread_queue.patch

build:
  number: 0
  string: py{{py}}cuda{{ environ['CUDA_VERSION'] }}_0

requirements:
  build:
    - cmake
    - gcc
    # cudatoolkit is not used in the build but is included to pin the
    # CUDA version and avoid mixing of CUDA runtimes.
    - cudatoolkit {{ environ['CUDA_VERSION'] }}*
  run:
    - cudatoolkit {{ environ['CUDA_VERSION'] }}*

about:
  home: http://icl.cs.utk.edu/magma/software/index.html
  license: BSD 3-Clause
  license_family: BSD
  license_file: COPYRIGHT
  summary: Matrix Algebra on GPU and Multicore Architectures
