{% set version = "0.1.12" %}

package:
  name: pytorch-cpu
  version: {{ version }}

source:
  fn: pytorch-{{ version }}.tar.gz
  url: https://github.com/pytorch/pytorch/archive/v{{ version }}.tar.gz
  sha256: ace32cc277c2f59b1e496e326bf504d800061edde9b6c2af29bbb2f08728ca30

build:
  number: 0
  features:
    - nomkl  [nomkl]
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - numpy
    - setuptools
    - pyyaml
    - mkl              [not nomkl]
    - cffi
    - gcc
    - cmake
    - openblas 0.2.19  [nomkl]

  run:
    - python
    - numpy
    - mkl 2017.0.*     [not nomkl]
    - cffi
    - libgcc
    - openblas 0.2.19  [nomkl]

test:
  imports:
    - torch
  source_files:
    - test
  commands:
    - ./test/run_test.sh

about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PyTorch is an optimized tensor library for deep learning, CPU only version.
