package:
  name: torchvision
  version: 0.1.8

source:
  git_url: https://github.com/pytorch/vision.git
  git_tag: v0.1.8

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - numpy
    - pillow
    - pytorch
    - setuptools
    - six

  run:
    - python
    - numpy
    - pillow
    - pytorch
    - six

test:
  imports:
    - torchvision
    - torchvision.datasets
    - torchvision.models
    - torchvision.transforms
    - torchvision.utils

about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image and video datasets and models for torch deep learning
